add variables
Yevhenii-Bezeha/bc-project-team-2 pull request #14
Opened 2021-07-25 11:52 UTC by NadiiaMatsko

додала змінні кольори. паддінги і марджини майже всюди різні. коли буду робити секцію, детальніше роздивлюся розміри і, якщо треба, зміню цей файл.

2021-07-25 17:42 UTC, 13dds13 reviewed
Нужно уточнить у Жени, что делать со строками 8 и 9. И нужно ли это вообще выносить в переменные, если да - тогда переименовать без привязки к конкретному цвету.

2021-07-25 17:42 UTC, 13dds13 commented on src/sass/base/_variables.scss
> +    $light-brown-color: #f0d1a5; // светло-коричневый цвет
Нужно постараться отойти от прямого указания цвета в переменной.  У самого с наименованием не оч, но нужно что-то придумать. Например, для салатового и следующей строки: section-bgc-one, -two и т.д.

2021-07-25 17:42 UTC, 13dds13 commented on src/sass/base/_variables.scss
> +    $grey-text-color: #907e82; // серый цвет текста
Тут тоже лучше указать что-то типа: main-text-color. А в комментариях удобно, что уточняется текущее значение этого цвета)

2021-07-25 18:11 UTC, Yevhenii-Bezeha requested changes

2021-07-25 18:11 UTC, Yevhenii-Bezeha commented on src/sass/base/_variables.scss
> +    $light-brown-color: #f0d1a5; // светло-коричневый цвет
Давайте отойдем от названий именно цветов, будем использовать, варианты, как main-text-color, section-products-bg-colour и так далее )

2021-07-25 23:50 UTC, 13dds13 approved these changes
Nice job)

2021-07-25 23:50 UTC, 13dds13 commented on src/sass/base/_variables.scss
>      $button-contacts-hover: #d41342; // цвет  ховера our locations
Это косяк дизайнера, для общих классов ховера кнопок эту переменную лучше не использовать.

2021-07-26 05:58 UTC, Yevhenii-Bezeha approved these changes

2021-07-26 05:58 UTC, merged